import { Inter } from "next/font/google";
import "./globals.css";
import Navigationbar from "@/components/Navigationbar/Navigationbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="main">
        <div className="navbar"> 
            <Navigationbar />
          </div>
          <div className="content">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
